version: "3"
services:
  ui:
    build: ui
    ports:
      - 8000:8000
    volumes:
      - ./ui/app:/app
      - ./tempweek.png:/app/public/tempweek.png
    depends_on:
      - api
  api:
    build: api
    command: python ./api.py
    ports:
      - 5000:5000
    volumes:
      - ./api/app:/app
      - ./manual.conf:/manual.conf
